apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  ca.crt: |+
    -----BEGIN CERTIFICATE-----
    MIIBbjCCARSgAwIBAgIQYFa6+Qjh0ze8b9IfzHlVPDAKBggqhkjOPQQDAjAXMRUw
    EwYDVQQDEwxrb21tYW5kZXItY2EwHhcNMjUwNDExMDEyNTI5WhcNMzUwNDA5MDEy
    NTI5WjAXMRUwEwYDVQQDEwxrb21tYW5kZXItY2EwWTATBgcqhkjOPQIBBggqhkjO
    PQMBBwNCAARz/npX5yJeUE0DQcS2Bv7HOqGYZnHKE/I9wEHPNuG86g9g1DtLIE95
    3seieNNqLgBwYa976op4q7V2rra36Jeio0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUtzl+0WWSWg7hLcXqbfU7znjLL5UwCgYI
    KoZIzj0EAwIDSAAwRQIhAJJl84PKblEBGEY+3joLs8MIFPOBqdEIOEdJ+CVSeAHr
    AiAHLaprwSGh4Up9NtO1TWlgSlSsnCQ8TIEjK0NLyX2T+g==
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
  namespace: kube-system
data:
  setup.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates && systemctl restart containerd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: node-custom-setup
  labels:
    k8s-app: node-custom-setup
spec:
  selector:
    matchLabels:
      k8s-app: node-custom-setup
  template:
    metadata:
      labels:
        k8s-app: node-custom-setup
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: debian
        env:
        - name: TRUSTED_CERT
          valueFrom:
            configMapKeyRef:
              name: trusted-ca
              key: ca.crt
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: setup-script
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1